import SwiftUI
import UserNotifications

/// Detects a launch triggered by the login item and hides the main window,
/// so booting the Mac brings up only the menu bar widget. Also routes
/// Memory Watch notification actions and starts its monitor.
final class AppDelegate: NSObject, NSApplicationDelegate, UNUserNotificationCenterDelegate {
    func applicationDidFinishLaunching(_ notification: Notification) {
        UNUserNotificationCenter.current().delegate = self
        MemoryWatch.shared.start()
        // Keep stats live for the menu bar label's usage bars.
        SystemStats.shared.start()
        DiskStatus.shared.startAutoRefresh()

        let event = NSAppleEventManager.shared().currentAppleEvent
        let launchedAtLogin = event?.eventID == kAEOpenApplication
            && event?.paramDescriptor(forKeyword: keyAEPropData)?.enumCodeValue == keyAELaunchedAsLogInItem
        if launchedAtLogin {
            DispatchQueue.main.async {
                NSApp.windows.filter { $0.canBecomeMain }.forEach { $0.close() }
            }
        }
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        MemoryWatch.handleAction(response.actionIdentifier,
                                 userInfo: response.notification.request.content.userInfo)
        completionHandler()
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler:
                                    @escaping (UNNotificationPresentationOptions) -> Void) {
        // Show alerts even while CleanUp is frontmost.
        completionHandler([.banner, .sound])
    }
}

@main
struct CleanUpApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var appDelegate
    @Environment(\.openWindow) private var openWindow

    /// Monochrome template icon: the logo shape extracted from menubar.png
    /// (generated by make_menubar_icon.swift into Resources/MenuBarIcon.png).
    /// As a template image, the menu bar tints it black or white automatically.
    static let menuBarIcon: NSImage = {
        guard let url = Bundle.main.url(forResource: "MenuBarIcon", withExtension: "png"),
              let image = NSImage(contentsOf: url) else {
            let fallback = NSImage(systemSymbolName: "wand.and.stars",
                                   accessibilityDescription: "CleanUp") ?? NSImage()
            fallback.isTemplate = true
            return fallback
        }
        image.size = NSSize(width: 18, height: 18)
        image.isTemplate = true
        return image
    }()

    var body: some Scene {
        WindowGroup(id: "main") {
            MainView()
                .frame(minWidth: 900, minHeight: 600)
        }
        .commands {
            CommandGroup(replacing: .appInfo) {
                Button("About CleanUp") { openWindow(id: "about") }
                Button("Check for Updates…") { Updater.shared.check(manual: true) }
            }
        }

        Window("About CleanUp", id: "about") {
            AboutView()
        }
        .windowResizability(.contentSize)

        MenuBarExtra {
            MenuBarContent()
        } label: {
            MenuBarLabel()
        }
        .menuBarExtraStyle(.window)
    }
}

/// The status-item icon: the logo, or live usage bars when the user opts in.
struct MenuBarLabel: View {
    @AppStorage("menuBarShowsBars") private var showBars = false
    @ObservedObject private var stats = SystemStats.shared
    @ObservedObject private var disk = DiskStatus.shared

    var body: some View {
        if showBars {
            Image(nsImage: MenuBarBars.image(cpu: stats.cpuPercent / 100,
                                             mem: stats.memFraction,
                                             disk: disk.usedFraction))
        } else {
            Image(nsImage: CleanUpApp.menuBarIcon)
        }
    }
}

struct MenuBarContent: View {
    @ObservedObject private var disk = DiskStatus.shared
    @ObservedObject private var stats = SystemStats.shared
    @StateObject private var loginItem = LoginItem()
    @AppStorage("menuBarShowsBars") private var showBars = false
    @State private var topProcesses: [ProcInfo] = []
    @State private var topMemProcesses: [ProcInfo] = []
    @Environment(\.openWindow) private var openWindow

    private let processTimer = Timer.publish(every: 5, on: .main, in: .common).autoconnect()

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("CleanUp").font(.headline)

            statRow(icon: "cpu", title: "CPU",
                    value: String(format: "%.0f%%", stats.cpuPercent),
                    fraction: stats.cpuPercent / 100)

            processList(topProcesses) { String(format: "%.0f%%", $0.cpuPercent) }

            statRow(icon: "memorychip", title: "Memory",
                    value: "\(Format.bytes(stats.memUsed)) of \(Format.bytes(stats.memTotal))",
                    fraction: Double(stats.memUsed) / Double(max(stats.memTotal, 1)))

            processList(topMemProcesses) { Format.bytes($0.memBytes) }

            statRow(icon: "internaldrive", title: "Disk free",
                    value: "\(disk.freeShort) of \(Format.bytes(disk.total))",
                    fraction: 1 - Double(disk.free) / Double(max(disk.total, 1)))

            Divider()

            Toggle("Launch at login", isOn: Binding(
                get: { loginItem.enabled },
                set: { loginItem.set($0) }
            ))
            .toggleStyle(.switch)
            .controlSize(.small)

            Toggle("Show usage bars in menu bar", isOn: $showBars)
                .toggleStyle(.switch)
                .controlSize(.small)
                .help("Replace the logo with live CPU / memory / disk bars — green low, blue normal, red high")
            if let error = loginItem.lastError {
                Text(error).font(.caption2).foregroundStyle(.red)
            }

            Divider()

            HStack {
                Button("Open CleanUp") {
                    NSApp.activate(ignoringOtherApps: true)
                    openWindow(id: "main")
                }
                Button("Smart Scan") {
                    NSApp.activate(ignoringOtherApps: true)
                    openWindow(id: "main")
                    AppState.shared.requestSmartScan()
                }
                .buttonStyle(.borderedProminent)
                Spacer()
                Button {
                    NSApp.terminate(nil)
                } label: {
                    Image(systemName: "power")
                }
                .help("Quit CleanUp")
            }
        }
        .padding(14)
        .frame(width: 280)
        .onAppear {
            disk.refresh()
            refreshProcesses()
        }
        .onReceive(processTimer) { _ in refreshProcesses() }
    }

    @ViewBuilder
    private func processList(_ procs: [ProcInfo], value: @escaping (ProcInfo) -> String) -> some View {
        if !procs.isEmpty {
            VStack(alignment: .leading, spacing: 4) {
                ForEach(procs) { proc in
                    HStack(spacing: 6) {
                        if let icon = proc.icon {
                            Image(nsImage: icon).resizable().frame(width: 14, height: 14)
                        } else {
                            Image(systemName: "gearshape")
                                .font(.system(size: 10)).frame(width: 14)
                        }
                        Text(proc.name).font(.caption).lineLimit(1)
                        Spacer()
                        Text(value(proc))
                            .font(.caption).monospacedDigit().foregroundStyle(.secondary)
                    }
                }
            }
            .padding(.leading, 24)
        }
    }

    private func refreshProcesses() {
        Task.detached(priority: .utility) {
            let (cpu, mem) = SpeedService.topProcesses(count: 3)
            await MainActor.run {
                topProcesses = cpu
                topMemProcesses = mem
            }
        }
    }

    @ViewBuilder
    private func statRow(icon: String, title: String, value: String, fraction: Double) -> some View {
        VStack(alignment: .leading, spacing: 3) {
            HStack {
                Label(title, systemImage: icon).font(.callout)
                Spacer()
                Text(value).font(.callout).monospacedDigit().foregroundStyle(.secondary)
            }
            ProgressView(value: min(max(fraction, 0), 1))
                .progressViewStyle(.linear)
                .tint(fraction > 0.85 ? .red : fraction > 0.65 ? .orange : .accentColor)
        }
    }
}
